### ISSUE TITLE
Transform function library

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane-runtime#131]
### What problem are you facing?

The design for application and infrastructure composition is still being finalised per https://github.com/crossplane/crossplane/issues/1344, but one thing that we've reached agreement on is the introduction of a simple, YAML native method to configure templates. This method involves taking a base object then patching it by overlaying field paths from another object. We'd like to support optional "transforms" as part of this overlay process, to allow the overlay values to be derived from rather than identical to their source values.

Here's two examples:

```yaml
    patches:
    - fromFieldPath: "spec.region"
      toFieldPath: "spec.forProvider.location"
      transforms:
      - type: map
        map:
          us-west: "West US"
          us-east: "East US"
```

```yaml
      transforms:
      - type: math
        math:
          multiply: 1024
```

### How could Crossplane help solve your problem?

crossplane-runtime could add a core API type (perhaps `runtimev1alpha1.Transforms`) that configured the transforms to apply, and a library that implemented them. My suggestion would be to start with a very small set of functions and expand them as needed - I suspect math and map may be sufficient. It may be worth investigating the built in functions of other configuration DSLs like Terraform and jsonnet for inspiration for other useful transform functions:

* https://www.terraform.io/docs/configuration/functions.html
* https://jsonnet.org/ref/stdlib.html
* https://github.com/google/starlark-go/blob/master/doc/spec.md#built-in-constants-and-functions
