### ISSUE TITLE
Deprecate the 'Synced' status condition

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane-runtime#198]
### What problem are you facing?

Most Crossplane resources (managed, claims, composites, etc) typically expose two types of status condition:

* `Ready` indicates whether the thing being reconciled (e.g. the external resource) is expected to be functional.
* `Synced` indicates whether the most recent reconcile attempt succeeded or failed, including any error.

Sometimes `Ready` goes by different names - e.g. `Established` for XRDs.

Originally Crossplane only had a `Ready` condition, but it was conceptually conflated with "synced" and attempted to reflect both whether the underlying resource was ready and whether Crossplane was successfully able to reconcile the underlying resource. The `Synced` condition has served us well for some time, but I think it should be removed because:

* It's duplicated by events. Anecdotally, we emit an event corresponding to ~95% of our `SetConditions` calls.
* It's duplicated by debug logs in the other ~5% of cases, which are 'internal' errors like being unable to remove a finalizer.
* It's a footgun when writing multiple controllers that reconcile the same kind of resource.

The apiextensions 'definition' and 'offered' controllers are examples of the latter issue. Both controllers collaborate to reconcile a `CompositeResourceDefinition`. The `definition` controller manages the lifecycle of the defined composite resource and its controller, while the `offered` controller manages the lifecycle of the offered resource claim (if any) and its controller. Currently both reconcilers attempt to set the `Synced` condition of the XRD; if one controller was reconciling successfully and the other was encountering an error they would get stuck in a tight reconcile loop.

### How could Crossplane help solve your problem?

I suggest we deprecate and stop using the `Synced` condition in any reconciler that has been updated to emit events and logs.

**Comment by muvaf** [comment]
I believe conditions are most useful in machine to machine communication, which is not really what events/logs are for. However, `Synced` doesn't really mean much for other controllers or systems, at least I haven't seen us writing code to check `Synced` condition, it's mostly the `Ready` one. So, in the places we're able to communicate that `there is a misconfiguration problem` to the user via another mechanism like event, I agree that we don't need `Synced` condition.

**Comment by muvaf** [comment]
Hmm, actually UI systems are usually built using YAML output of the resources, which do not have the events. So that's a machine usage of the `Synced` condition; to show user that there is a misconfiguration through the UI. I believe Upbound Cloud is built this way. I went to look at `Pod` to see what conditions it has:
```yaml
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-09-03T15:12:15Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-09-10T07:54:42Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-09-10T07:54:42Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-09-03T15:12:15Z"
    status: "True"
    type: PodScheduled
```
From what I can tell, there is an abundance of conditions which also have corresponding events published. So, it comes down to whether we'd like the YAML, i.e. etcd record of the resource, to fully represent everything we know about it at the time of printing or not. I generally lean towards abundance of information as long as it's easy to keep it all in sync. Maybe merge errors that we report under `Synced` into `Ready` condition? i.e. `look at Ready condition for all kinds of errors we are able to report`?
