### ISSUE TITLE
Support Filesystem and Environment CredentialsSource in ProviderConfig

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane-runtime#236]
### What problem are you facing?

Crossplane providers all currently support a `ProviderConfig` type that specifies how the provider should obtain credentials for a given reconcile operation. These `ProviderConfig`s typically embed the [ProviderConfigSpec](https://github.com/crossplane/crossplane-runtime/blob/c674db318cdb5bd326bab5595fd94fa11293cb3a/apis/common/v1/resource.go#L178) struct, which has common credentials sources, such as `Secret`, `InjectedIdentity`, and `None`. However, there are other ways that credentials may be injected into a provider `Pod` that do not currently fall into these categories. While providers are not required to implement this exact `ProviderConfigSpec`, it should include common credentials sources to allow for more providers to use it directly.

### How could Crossplane help solve your problem?

Two of the most common sources for credentials are injection in the container's filesystem and setting of environment variables. These may be done directly using something like [`ContollerConfig`](https://doc.crds.dev/github.com/crossplane/crossplane/pkg.crossplane.io/ControllerConfig/v1alpha1@v1.0.0), or by an external system, such as the [Vault agent's mutating webhook](https://learn.hashicorp.com/tutorials/vault/agent-kubernetes). The `ProviderConfigSpec` should support `CredentialsSource` of `Filesystem` and `Environment` for these use-cases, as well as embed `fs` and `env` structs for specifying how to extract the credentials. Examples for each are shown below:
```yaml
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: from-fs
spec:
  credentials:
    source: Filesystem
    fs:
      path: /crossplane/secrets/aws-creds.txt
---
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: from-env
spec:
  credentials:
    source: Environment
    env:
      name: MY_AWS_CREDS
``` 

`crossplane-runtime` should also provide common functions for extracting these values, such that the `Connect` methods can be simplified for reconciliation loops written in each provider. This would likely take the form of an engine that accepted a `ProviderConfigSpec` and had handlers for extracting `Filesystem`, `Environment`, and `Secret` credentials sources, then accepted additional handlers for provider-specific sources, such as `InjectedIdentity`, or overriding the previously mentioned handlers.

One area this design is still slightly rough is when a provider wants to go outside the bounds of the common `ProviderConfigSpec` functionality. A good example of this is if a `provider-aws` user wanted to use an injected SA token for IRSA for two separate roles (see example [here](https://github.com/aws/amazon-eks-pod-identity-webhook/issues/32#issuecomment-588113740)). It would be nice to be able to provide a custom struct such as `irsaOverrides`:

```yaml
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: other-irsa
spec:
  credentials:
    source: InjectedIdentity
    irsaOverrides:
      awsRoleArnEnvVar: AWS_ROLE_ARN_WEST
```

However, this would not be possible with the current `ProviderConfigSpec` if used directly (this is not a new restriction, but rather the current status of the `ProviderConfigSpec` design). As mentioned above, there is always the opportunity for a provider to not use the `ProviderConfigSpec`, but it is highly encouraged. Options to make this a more seamless experience could be to mix and match source and struct:

```yaml
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: other-irsa
spec:
  credentials:
    source: InjectedIdentity
    env:
      name: AWS_ROLE_ARN_2 # provider-aws knows this overrides AWS_ROLE_ARN when InjectedIdentity is specified
```

Or to encourage only the embedding of the [`ProviderCredentials` struct](https://github.com/crossplane/crossplane-runtime/blob/c674db318cdb5bd326bab5595fd94fa11293cb3a/apis/common/v1/resource.go#L204), have that passed to the aforementioned "handler engine", then allow the provider to define other fields in the spec:

```yaml
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: other-irsa
spec:
  credentials:
    source: InjectedIdentity
  irsaOverrides: # note this now lives at same level as credentials in the spec as opposed to nested under it
    awsRoleArnEnvVar: AWS_ROLE_ARN_WEST
```

I think this model would be my preference, and could be done without actually impacting the current API of `ProviderConfig` in each provider.

cc @negz @muvaf @kasey @prasek

**Comment by hasheddan** [comment]
Wondering if maybe we should drop the [`CredentialsSource` enum](https://github.com/crossplane/crossplane-runtime/blob/c674db318cdb5bd326bab5595fd94fa11293cb3a/apis/common/v1/resource.go#L206) and have the handler engine just match on a string. That means, unless overridden, every `ProviderConfig` would support `None`, `Secret`, `InjectedIdentity` out of the box, but addition "native" types could be added. One I am thinking immediately is [`AssumeRoleWithSAML`](https://docs.aws.amazon.com/sdk-for-go/api/service/sts/#STS.AssumeRoleWithSAML), where it might be nice for `provider-aws` to be able to look like:

```
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: other-irsa
spec:
  credentials:
    source: SAML
  samlToken:
    path: /path/to/where/saml/token/mounted
```

**Comment by muvaf** [comment]
How about embedding `ProviderCredentials` with a slight modification instead of `ProviderConfigSpec`. The structs in crossplane-runtime would look like the following:
```golang
// ProviderCredentials required to authenticate.
type ProviderCredentials struct {
	// Source of the provider credentials.
	Source string `json:"source"`

	// A CredentialsSecretRef is a reference to a secret key that contains the
	// credentials that must be used to connect to the provider.
	// +optional
	SecretRef *SecretKeySelector `json:"secretRef,omitempty"`

	Env *EnvSelector `json:"env,omitempty"`

	Fs *FsSelector `json:"fs,omitempty"`
}

type EnvSelector struct {
	Name string `json:"name,omitempty"`
}

type FsSelector struct {
	Path string `json:"path,omitempty"`
}
```

Note that `Source` is of `string` type now to allow providers use whatever string they want as long as they can work with it.

Then in, say provider-aws, the `ProviderConfigSpec` would look like the following:
```golang
const (
	CredentialsSourceIRSA = "IRSA"
)

// A ProviderConfigSpec defines the desired state of a ProviderConfig.
type ProviderConfigSpec struct {
	Credentials ProviderCredentials `json:"credentials,omitempty"`
}

type ProviderCredentials struct {
	xpv1.ProviderCredentials `json:",inline"`

	IRSAField *string `json:"irsaField,omitempty"`
}
```

This should allow providers to use any custom additional source they want and change shouldn't be breaking. SAML example could look like:
```yaml
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: other-irsa
spec:
  credentials:
    source: SAMLPath
    samlPath: /path/to/where/saml/token/mounted
---
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: other-irsa
spec:
  credentials:
    source: SAMLToken
    samlToken: # provider can choose how the struct looks like.
      path: /path/to/where/saml/token/mounted
      secretRef:
        name: saml-secret
       namespace: saml-ns
        key: token
      env: MY_SAML_TOKEN
```
