### ISSUE TITLE
Select ProviderConfig via labels

### ISSUE THREAD

**Issue by MisterMX** [crossplane/crossplane-runtime#319]
### What problem are you facing?

Crossplane managed resources currently support referencing a `ProviderConfig` via its object name through `spec.providerConfigRef.name`.

This requires the name to be known when creating the MR. However, this is not always the case. For example, if one creates an EKS cluster through a composition that also generates a new `helm.crossplane.io/ProviderConfig`, the name will have a dynamic hash appended as prefix. In this case one would have to wait for the composite resource and copy-paste the name before deploying resources on the cluster.

### How could Crossplane help solve your problem?

Since one can add the composite labels to the `ProviderConfig` such as `crossplane.io/claim-name` and `crossplane.io/claim-namespace` one could select the respective provider config using this labels.

This way I could install a helm `Release` by referencing the config through a `providerConfigSelector`, i.e.

```yaml
apiVersion: helm.crossplane.io/v1beta1
kind: Release
spec:
  forProvider:
    # ...
  providerConfigSelector:
    matchLabels:
       crossplane.io/claim-name: my-cluster
       crossplane.io/claim-namespace: my-project
```
